use_frameworks!

platform :ios, '8.0'

target 'NWNComponent_Example' do
  pod 'NWNComponent', :path => '../'

  target 'NWNComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
